name: application
description: Skadate mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Slidable list item implementation.
  flutter_slidable: ^0.6.0

  flutter_math_fork: ^0.5.0

  # List that allows to programmatically scroll to a specific item.
  scrollable_positioned_list: 0.2.0-nullsafety.0 

  # Launches URLs.
  url_launcher: ^6.0.9

  # Caches internet images.
  cached_network_image: ^3.1.0

  # Tinder cards (a customized version).
  tcard:
    git: https://github.com/skalfa/tcard

  # Facebook sign-in library, used with Firebase auth.
  flutter_facebook_auth: ^3.5.1

  # Google sign-in library, used with Firebase auth.
  google_sign_in: ^5.0.7

  # Core Firebase package.
  firebase_core: ^1.6.0

  # Firebase Auth package.
  firebase_auth: ^3.1.0

  # Firebase Cloud Messaging package, used for Push notifications.
  firebase_messaging: ^10.0.6

  # Firebase Analytics integration.
  firebase_analytics: ^8.3.1

  # Converts HTML to Flutter widgets, used to display HTML content.
  flutter_html: ^2.1.1

  # Toasts for Flutter.
  another_flushbar: ^1.10.24

  # File picker dialog.
  file_picker: ^4.0.0

  # Defines annotations used by json_serializable to generate code for JSON serialization.
  json_annotation: ^4.6.0

  # Automatically choose between Material and Cupertino widgets based on the host platform.
  flutter_platform_widgets: ^1.9.5

  # Simplified styling syntax.
  styled_widget: ^0.3.1+2

  # Internet connection state watcher.
  connectivity: ^3.0.6

  # Platform-specific persistent storage wrapper for key-value data.
  shared_preferences: ^2.0.7

  # Platform-independent parsing and serialization of HTTP formats.
  http_parser: ^4.0.0

  # HTTP client.
  dio: ^4.0.0

  # Routing library.
  fluro: ^2.0.3

  # `sprintf` function.
  sprintf: ^6.0.0

  # Service Locator pattern implementation.
  get_it: ^7.2.0

  # Reactive state management library.
  mobx: ^2.0.4

  # Flutter integration for MobX.
  flutter_mobx: ^2.0.2

  # JWT decoder.
  jwt_decoder: ^2.0.1

  # WebRTC plugin for Flutter based on GoogleWebRTC.
  flutter_webrtc: ^0.6.10+hotfix.1

  # Host device information.
  device_info: ^2.0.3

  # Host browser detector for Flutter Web.
  browser_detector: ^2.0.0

  # Admob integration.
  google_mobile_ads: ^0.13.4

  # Turns URLs and emails into clickable links in text.
  flutter_linkify: ^5.0.2

  # A user location detector 
  geolocator: ^7.5.0

  # Audio player.
  just_audio: ^0.9.7

  # Flutter bridge to Sign in with Apple.
  sign_in_with_apple: ^3.2.0

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  crypto: ^3.0.1

  # Utility functions and classes to make working with collections easier.
  collection: ^1.15.0-nullsafety.4

  # Deep links and custom URL schemes support.
  uni_links: ^0.5.1

  # Stores the pushed and popped routes history.
  navigation_history_observer: ^1.1.0

  # Selects pictures from the Android and iOS image library, optionally can take new pictures using
  # camera.
  image_picker: ^0.8.3+3

  # Utilities for handling MIME types, incl. determining file type from its extension or content.
  mime: ^1.0.0

  # Platform-independent native purchases API.
  in_app_purchase: ^3.0.7
  
  # Native keyboard status watcher.
  flutter_keyboard_visibility: ^5.0.3

  # Centralized log and crash report analysis service.
  sentry_flutter: ^5.1.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
 
dependency_overrides:
  in_app_purchase_android: ^0.2.3+3

dev_dependencies:
  # Automatic JSON (de-)serialization code generator.
  json_serializable: ^6.3.1

  # Launcher icon builder.
  flutter_launcher_icons: ^0.9.2

  # Flutter native splash screen customization.
  flutter_native_splash: ^1.2.1

  # Build system for code generation and modular compilation.
  build_runner: ^2.1.1

  # MobX store code generator.
  mobx_codegen: ^2.0.1+3

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. 
  uses-material-design: true

  fonts:
    - family: SkMobileFont
      fonts:
        - asset: assets/font/SkMobileFont.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/app/
    - assets/image/app/2.0x/
    - assets/image/app/3.0x/
    - assets/image/common/
    - assets/image/common/2.0x/
    - assets/image/common/3.0x/
    - assets/image/installation_guide/ 
    - assets/image/login/ 
    - assets/image/login/2.0x/
    - assets/image/login/3.0x/
    - assets/image/edit/
    - assets/image/edit/2.0x/
    - assets/image/edit/3.0x/
    - assets/image/payment/
    - assets/image/payment/billing_gateways/
    - assets/sound/video_im/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf 
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
