/// Flutter icons SkMobileFont
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SkMobileFont
///      fonts:
///       - asset: fonts/SkMobileFont.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SkMobileFont {
  SkMobileFont._();

  static const _kFontFam = 'SkMobileFont';
  static const String? _kFontPkg = null;

  static const IconData lock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_alert = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_pending = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_not_found = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_no_permission = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_success = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_dashboard_user = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_hotlist = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_maintenance = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_location = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_attachment = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_payment_processing = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_clock = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_dislike = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_no_memberships = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_match_keep_play = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_no_credits = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_message_error = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_3_card = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_dashboard = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_hotlist = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_messages = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_search_filter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_tinder_cards = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_rewind = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_wink = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile_bookmark = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile_message = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile_video_chat = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_match_send_message = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_down = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_card = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_app_error = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_no_internet = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_chat = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_like = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_profile = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_search = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_2_card = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_2_hotlist = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_2_messages = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_2_search = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_3_dashboard_active = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_3_dashboard_passive = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_3_hotlist = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_3_messages = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_card = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_dashboard = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_hotlist = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_messages = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_card = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_dashboard = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_hotlist = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_messages = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_search = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_bookmark = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_dislike = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_up = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_login = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_login = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_4_password = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_password = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_card_passive = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_dashboard_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_1_hotlist_passive = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_down = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_up = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_3_messages_active = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_5_settings = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
